server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Dani}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:MySuperSecretKeyForJwt12345678901234567890}
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:daniradu374@gmail.com}
spring.mail.password=${MAIL_PASSWORD:qugg hqwn mnqi maoq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=${APP_FRONTEND_URL:http://localhost:5173}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}